"""Initial

Revision ID: ef4d6d75421f
Revises: 8fa5da923cd1
Create Date: 2021-12-14 02:18:49.459391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4d6d75421f'
down_revision = '8fa5da923cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
